[package]
name = "asm-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
asm-core = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
jiff = { workspace = true }
serde_json = { workspace = true }
etcetera = { workspace = true }
sha2 = { workspace = true }
